/**
 * generated by Xtext 2.18.0.M3
 */
package io.github.abelgomez.asyncapi.asyncApi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OR Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getORCondition()
 * @model
 * @generated
 */
public interface ORCondition extends BooleanCondition
{
} // ORCondition
