/**
 * generated by Xtext 2.18.0.M3
 */
package io.github.abelgomez.asyncapi.asyncApi;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Qo SMetric</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getName <em>Name</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getMetricType <em>Metric Type</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getDescription <em>Description</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getUnit <em>Unit</em>}</li>
 *   <li>{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getDataType <em>Data Type</em>}</li>
 * </ul>
 *
 * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getQoSMetric()
 * @model
 * @generated
 */
public interface QoSMetric extends AbstractQoSMetric
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getQoSMetric_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Metric Type</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.abelgomez.asyncapi.asyncApi.QoSMetricName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metric Type</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.QoSMetricName
   * @see #setMetricType(QoSMetricName)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getQoSMetric_MetricType()
   * @model
   * @generated
   */
  QoSMetricName getMetricType();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getMetricType <em>Metric Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metric Type</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.QoSMetricName
   * @see #getMetricType()
   * @generated
   */
  void setMetricType(QoSMetricName value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getQoSMetric_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.abelgomez.asyncapi.asyncApi.QoSMetricUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.QoSMetricUnit
   * @see #setUnit(QoSMetricUnit)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getQoSMetric_Unit()
   * @model
   * @generated
   */
  QoSMetricUnit getUnit();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.QoSMetricUnit
   * @see #getUnit()
   * @generated
   */
  void setUnit(QoSMetricUnit value);

  /**
   * Returns the value of the '<em><b>Data Type</b></em>' attribute.
   * The literals are from the enumeration {@link io.github.abelgomez.asyncapi.asyncApi.QoSMetricType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Type</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.QoSMetricType
   * @see #setDataType(QoSMetricType)
   * @see io.github.abelgomez.asyncapi.asyncApi.AsyncApiPackage#getQoSMetric_DataType()
   * @model
   * @generated
   */
  QoSMetricType getDataType();

  /**
   * Sets the value of the '{@link io.github.abelgomez.asyncapi.asyncApi.QoSMetric#getDataType <em>Data Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Type</em>' attribute.
   * @see io.github.abelgomez.asyncapi.asyncApi.QoSMetricType
   * @see #getDataType()
   * @generated
   */
  void setDataType(QoSMetricType value);

} // QoSMetric
